data_type: yaml
data_config:
  file_root_path: .\test_data
  file_pattern: ["*.yaml"]
  encoding: utf-8

template_type: jinja
template_config:
  template_dir: .\template
  autoescape: false

pattern:
  - "c/*.yaml"

output_dir: .\output\test
output_file_extension: c

preserved_template_key: TEMPLATE_PATH
preserved_children_key: CHILDREN_PATH
preserved_children_content_key: CHILDREN_CONTEXT
