data_type: yaml
data_config:
  file_root_path: .\source\data
  file_pattern: ["*.yaml"]
  encoding: utf-8

template_type: jinja
template_config:
  template_dir: .\source\template
  autoescape: false

pattern:
  - "*.yaml"

output_dir: .\source\output
output_file_extension: "xml"

preserved_template_key: TEMPLATE
preserved_children_key: CHILDREN
preserved_children_content_key: CHILDREN_CONTENT
