data_type: yaml
data_config:
  root_path: U:\Users\Enlink\Documents\code\python\Xdm\modules\test\expr_test\data
  file_pattern: ["*.yaml"]

template_type: jinja
template_config:
  template_dir: U:\Users\Enlink\Documents\code\python\Xdm\modules\test\expr_test\template
  autoescape: false

pattern:
  - "*.yaml"

output_dir: ../test/test_data/output

preserved_template_key: TEMPLATE
preserved_children_key: CHILDREN
preserved_children_content_key: CHILDREN_CONTENT
